In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [47]:
#https://www.kaggle.com/datasets/dragonheir/logistic-regression
#NO HAY INFORMACIÓN SOBRE LA DATA O QUE NOS PUEDA DAR INFORMACIÓN SOBRE QUE ES LO QUE SE PRETENDE ESTIMAR POR LO QUE SE 
#TRATARA DE RESPONDER A SI ES QUE HAN REALIZADO UNA COMPRA O NO, SIENDO 1 QUE SI HA REALIZADO COMPRA Y 0 SIENDO QUE NO SE HA 
#REALIZADO NINGUNA COMPRA, LAS VARIABLES QUE SE UTILIZARAN SERAN GENERO, EDAD, SALARIO ESTIMADO Y SE DESESTIMARA LA VARIABLE ID
df=pd.read_csv('Social_Network_Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [48]:
#SE SELECCIONAN LAS VARIABLES DE INTERES PARA LA CREACIÓN DE UN NUEVO DF Y SE CREA VARIABLE DUMMY PARA LAS VARIABLES CATEGORICAS
#SE REACOMODAN LAS NUEVAS VARIABLES Y SE MUESTRA EL DF NUEVO
Data=df[['Gender', 'Age', 'EstimatedSalary']]
Data['Male']=(Data['Gender']=='Male').astype(int)
Data['Female']=(Data['Gender']=='Female').astype(int)
Data.drop('Gender',axis=1,inplace=True)
Data=Data[['Male','Female','Age','EstimatedSalary']]
Data.head()

C:\Users\dell\AppData\Local\Temp\ipykernel_10204\652995940.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Male']=(Data['Gender']=='Male').astype(int)


Male  Female  Age  EstimatedSalary
0     1       0   19            19000
1     1       0   35            20000
2     0       1   26            43000
3     0       1   27            57000
4     1       0   19            76000

In [49]:
#SE CREA UNA SERIE CON LA VARIABLE DE INTERES A PREDECIR 
Y=df['Purchased'].values
Y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [50]:
#SE CREA EL NUMPY ARRAY CON LAS VARIABLES DEL DF QUE SE UTILIZAZARAN PARA PREDECIR Y SE LE AGREGARA UNA COLUMNA PARA QUE 
#FUNGA COMO EL BIAS
X=Data.values
X=np.c_[np.ones((len(X),1)),X]

In [51]:
#CREAR UN VECTOR PARA LOS PESOS Y EL BIAS
theta=np.zeros((len(X[0]),1))
theta

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

# Definir función Sigmoide

$S(x)=\frac{1}{1+e^{-x}}$

In [100]:
import math
def Sigmoide(X):
    sig=1/(1+math.e**(-X))
    return sig

# Definir función de Regresión logistica

In [53]:
def Regresion_Logistica(X,y,theta,alpha,epochs):
    y=np.reshape(y,(len(y),1))
    N=len(X)
    Loss_List=[]
    for epoch in range(epochs):
        sigXtheta=Sigmoide(np.dot(X,theta))
        gradiente=(1/N)*np.dot(np.transpose(X),sigXtheta-y)
        theta=theta-alpha*gradiente
        hyp=Sigmoide(np.dot(X,theta))
        loss= -np.sum(np.dot(np.transpose(y),np.log(hyp)+np.dot(np.transpose(1-y),np.log(1-hyp))))/len(hyp)
        Loss_List.append(loss)
    plt.plot(np.arange(1, epochs), Loss_List)
    plt.title('Cost function')
    plt.xlabel('Epochs')
    plt.ylabel('Cost')
    plt.show()
    return theta
        

In [95]:
epochs = 100000
alpha = 1
#Regresion_Logistica(X, Y, theta, alpha, epochs)

In [101]:
#EL VECTOR X TIENE FORMA DE (N,5)
theta=np.ones((len(X[0]),1)) #EL VECTOR THETA TIENE FORMA (5,1)
Y=np.reshape(Y,(len(Y),1)) #DARELE FORMA AL VECTOR DE (N,1)
N=len(X)
sigXtheta=Sigmoide(np.dot(X,theta)) #HACER LA FUNCIÓN SIGMOIDE DEL PRODUCTO ENTRE X Y THETA RESULTANDO EN UN VECTOR (N,1)
grad=(1/N)*np.dot(np.transpose(X),sigXtheta-Y) #HACER LA MULTIPLICACIÓN DE X' (5,N) POR SIGTHETA (N,1) RESULTANDO EN (5,1) 
theta=theta-(alpha*grad) #SE ACTUALIZA LA VARIABLE THETA DE ACUERDO AL ALPHA MANETENIENDO (5,1)
hyp=Sigmoide(np.dot(X,theta)) #SE CALCULA LA FUNCIÓN SIGMOIDE DEL PP ENTRE X (N,5) Y THETA (5,1) RESULTANDO EN (N,1)
#loss=(-1/N)*np.sum(np.dot(np.transpose(Y),np.log(hyp)+np.dot(np.transpose(1-Y),np.log(1-hyp))))


C:\Users\dell\AppData\Local\Temp\ipykernel_10204\47905820.py:3: RuntimeWarning: overflow encountered in power
  sig=1/(1+math.e**(-X))


In [102]:
hyp

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [98]:
np.dot(X,theta)

array([[-7.39081380e+08],
       [-7.77980701e+08],
       [-1.67265752e+09],
       [-2.21724354e+09],
       [-2.95632438e+09],
       [-2.25614254e+09],
       [-3.26751654e+09],
       [-5.83485064e+09],
       [-1.28366750e+09],
       [-2.52843570e+09],
       [-3.11192052e+09],
       [-2.02274852e+09],
       [-3.34531440e+09],
       [-7.00182641e+08],
       [-3.18971836e+09],
       [-3.11192058e+09],
       [-9.72475942e+08],
       [-1.01137490e+09],
       [-1.08917292e+09],
       [-1.12807196e+09],
       [-8.55778902e+08],
       [-1.90605194e+09],
       [-1.59485996e+09],
       [-8.55778902e+08],
       [-8.94677922e+08],
       [-7.77980942e+08],
       [-1.08917298e+09],
       [-1.16697094e+09],
       [-1.67265758e+09],
       [-7.00182621e+08],
       [-2.87852662e+09],
       [-5.32916354e+09],
       [-6.22384420e+08],
       [-1.71155656e+09],
       [-3.50091054e+09],
       [-1.05027370e+09],
       [-1.08917266e+09],
       [-1.90605160e+09],
       [-2.8